web:
  image: hector_web
  volumes:
    - .:/usr/src/app/:rw
  ports:
    - "8000:3000"
  expose:
    - "3000"
  environment:
    - NODE_ENV=dev
  command: >
    sh -c '
      npm run start:noauth;
    '
